WazeCredit/Models/ErrorViewModel.cs
namespace WazeCredit.Models;

public class ErrorViewModel
{
	public string? RequestId { get; set; }

	public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WazeCredit/Models/LoanApplication.cs
using System.ComponentModel.DataAnnotations;

namespace WazeCredit.Models;

public class LoanApplication
{
    public int Id { get; set; }
    [Required]
    public string SSN { get; set; }
    [DataType(DataType.Date)]
    public DateTime DOB { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    [Required]
    public int PostalCode { get; set; }
    [Required]
    public double Salary { get; set; }
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; }
    [DataType(DataType.PhoneNumber)]
    public string Phone { get; set; }
    public string Name { get; set; }
    public double CreditApproved { get; set; }
}

WazeCredit/Models/LoanApprovedEnum.cs
namespace WazeCredit.Models;

public enum LoanApprovedEnum
{
	Low, High
}

WazeCredit/Models/MarketCondition.cs
namespace WazeCredit.Models;

public enum MarketCondition
{
	StableUp,
	StableDown,
	Volatile
}

WazeCredit/Models/MarketResult.cs
namespace WazeCredit.Models;

public class MarketResult
{
	public MarketCondition MarketCondition { get; set; }
}

WazeCredit/Models/ViewModels/HomeViewModel.cs
namespace WazeCredit.Models.ViewModels;

public class HomeViewModel
{
	public string MarketForcast { get; set; }
}

WazeCredit/Models/ViewModels/LoanResult.cs
namespace WazeCredit.Models.ViewModels;

public class LoanResult
{
    public bool Success { get; set; }
    public IEnumerable<String> ErrorList { get; set; }
    public int CreditID { get; set; }
    public double CreditApproved { get; set; }
}

WazeCredit/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using WazeCredit.Data;
using WazeCredit.Models;
using WazeCredit.Models.ViewModels;
using WazeCredit.Service;
using WazeCredit.Service.Interfaces;
using WazeCredit.Utility.AppSettingsClasses;

namespace WazeCredit.Controllers;
public class HomeController : Controller
{
	public HomeViewModel _homeVM { get; set; }
	private readonly ILogger _logger;
	private readonly ApplicationDbContext _db;
	private readonly IMarketForcaster _marketForecaster;
	private readonly StripeSettings _stripeOptions;
	private readonly SendGridSettings _sendGridOptions;
	private readonly TwilioSettings _twilioOptions;
	private readonly WazeForecastSettings _wazeOptions;
	private readonly ILoanValidator _loanValidator;
	[BindProperty]
	public LoanApplication LoanModel { get; set; }

	public HomeController(ILogger<HomeController> logger,
		ApplicationDbContext db,
		IMarketForcaster marketForecaster,
		IOptions<WazeForecastSettings> wazeOptions,
		ILoanValidator loanValidator
		)
	{
		_homeVM = new HomeViewModel();
		_db = db;
		_logger = logger;
		_marketForecaster = marketForecaster;
		_wazeOptions = wazeOptions.Value;
		_loanValidator = loanValidator;
	}

	public IActionResult Index()
	{
		_logger.LogInformation("Home Controller Index Action Called");
		var currentMarket = _marketForecaster.GetMarketPrediction();

		switch (currentMarket.MarketCondition)
		{
			case MarketCondition.StableDown:
				_homeVM.MarketForcast = "Market shows signs to go Down";
				break;
			case MarketCondition.StableUp:
				_homeVM.MarketForcast = "Market shows signs to go Up";
				break;
			case MarketCondition.Volatile:
				_homeVM.MarketForcast = "Market shows signs of Volatility";
				break;
			default:
				_homeVM.MarketForcast = "Apply for a discount!";
				break;
		}

		_logger.LogInformation("Home Controller Index Action Ended");
		return View(_homeVM);
	}

	public IActionResult AllConfigSettings(
		[FromServices] IOptions<StripeSettings> stripeOptions,
		[FromServices] IOptions<SendGridSettings> sendGridOptions,
		[FromServices] IOptions<TwilioSettings> twilioOptions
		)
	{
		var messages = new List<string>();
		messages.Add($"Waze config: " + _wazeOptions.ForecastTrackerEnabled);
		messages.Add($"Stripe PubKey: " + stripeOptions.Value.PublishableKey);
		messages.Add($"Stripe SecretKey: " + stripeOptions.Value.SecretKey);
		messages.Add($"SendGrid Key: " + sendGridOptions.Value.SendGridKey);
		messages.Add($"Twilio Phone: " + twilioOptions.Value.PhoneNumber);
		messages.Add($"Twilio SID: " + twilioOptions.Value.AccountSid);
		messages.Add($"Twilio Token: " + twilioOptions.Value.AuthToken);

		return View(messages);
	}

	public IActionResult LoanApplication()
	{
		LoanModel = new LoanApplication();
		return View(LoanModel);
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	[ActionName("LoanApplication")]
	public async Task<IActionResult> LoanApplicationPOST(
		[FromServices] Func<LoanApprovedEnum, ILoanApproved> _loanService)
	{
		if(ModelState.IsValid)
		{
			var (validationPassed, errorMessages) = await _loanValidator.PassAllValidations(LoanModel);
			var loanResult = new LoanResult()
			{
				ErrorList = errorMessages,
				CreditID = 0,
				Success = validationPassed
			};
			if (validationPassed)
			{
				LoanModel.CreditApproved = _loanService(
					LoanModel.Salary > 50000 ? 
					LoanApprovedEnum.High : LoanApprovedEnum.Low)
					.GetLoanApproved(LoanModel);
				_db.LoanApplicationModel.Add(LoanModel);
				_db.SaveChanges();
				loanResult.CreditID = LoanModel.Id;
				loanResult.CreditApproved = LoanModel.CreditApproved;
			}
			return RedirectToAction(nameof(LoanResult), loanResult);
		}
		return View(LoanModel);
	}

	public IActionResult LoanResult(LoanResult loanResult)
	{
		return View(loanResult);
	}

	public IActionResult Privacy()
	{
		return View();
	}

	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error()
	{
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

WazeCredit/Controllers/LifeTimeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using WazeCredit.Models;
using WazeCredit.Models.ViewModels;
using WazeCredit.Service;
using WazeCredit.Service.Interfaces;
using WazeCredit.Service.LifeTimeExamples;
using WazeCredit.Utility.AppSettingsClasses;

namespace WazeCredit.Controllers;
public class LifeTimeController : Controller
{
	private readonly SingletonService _singletonService;
	private readonly ScopedService _scopedService;
	private readonly TransientService _transientService;

	public LifeTimeController(SingletonService singletonService, ScopedService scopedService, TransientService transientService)
	{
		_singletonService = singletonService;
		_scopedService = scopedService;
		_transientService = transientService;
	}

	public IActionResult Index()
	{
		var messages = new List<string>
		{
			HttpContext.Items["CustomMiddlewareSingleton"].ToString(),
			$"Singleton Controller - {_singletonService.GetGuidAsString()}",
			HttpContext.Items["CustomMiddlewareScoped"].ToString(),
			$"Scoped Controller - {_scopedService.GetGuidAsString()}",
			HttpContext.Items["CustomMiddlewareTransient"].ToString(),
			$"Transient Controller - {_transientService.GetGuidAsString()}"
		};

		// Remember, by default, use Transient!
		// It you think Scoped will do it, go for it,
		// Be carefull when using Singleton (stay the same during the lifetime of the app, and stays in the memory).

		return View(messages);
	}


}

WazeCredit/Views/Home/AllConfigSettings.cshtml
@model List<String>
@{
    ViewData["Title"] = "Index";
}

<div class="p-4">
    <h3>Configuration from AppSettings</h3>
    <ul>
        @foreach(var message in @Model)
        {
            <li>@message</li>
        }
    </ul>
</div>



@*<h1>Index</h1>
@{
    var count = 0;
}
@foreach (string mess in Model)
{
    if (count == 0)
    {
<div style="font-size:20px;padding-top:20px;">
    Transient Lifetime will be different for every request!
</div>
    }
    if (count == 2)
    {
        <div style="font-size:20px;padding-top:20px;">
            Scoped Lifetime will be different when you refresh! 
        </div>
    }
    if (count == 4)
    {
        <div style="font-size:20px;padding-top:20px;">
            Singleton Lifetime will be same for your application! It changes when the application restarts!
        </div>
    }
    count++;
    <div>
        @mess
    </div>
}*@

WazeCredit/Views/Home/Index.cshtml
@model WazeCredit.Models.ViewModels.HomeViewModel
@using Microsoft.Extensions.Options
@inject IOptions<WazeCredit.Utility.AppSettingsClasses.WazeForecastSettings> wazeForecastSettings
@*To Retrive session values:
- register the IHttpContext in Startup.cs
- you can inject the Session service in the view directly*@
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpContext

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>@Model.MarketForcast</p>
    <p>Currnet Marker Prediction: @(wazeForecastSettings.Value.ForecastTrackerEnabled ? "Online" : "Offline")</p>
</div>

WazeCredit/Views/Home/LoanApplication.cshtml
@model WazeCredit.Models.LoanApplication

<form method="post">
    <div class="container">
        <div class="row p-4 m-4 backgroundWhite border">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                <h2 class="text-info p-2 pb-4">Submit Loan Application</h2>
            </div>
            <div class="col-8 pt-3">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="Name" />
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Email"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="Email" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Phone"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="Phone" />
                        <span class="text-danger" asp-validation-for="Phone"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="SSN"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="SSN" />
                        <span class="text-danger" asp-validation-for="SSN"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="DOB"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="DOB" />
                        <span class="text-danger" asp-validation-for="DOB"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Salary"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="Salary" />
                        <span class="text-danger" asp-validation-for="Salary"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Address"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="Address" />
                        <span class="text-danger" asp-validation-for="Address"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="City"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="City" />
                        <span class="text-danger" asp-validation-for="City"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="State"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="State" />
                        <span class="text-danger" asp-validation-for="State"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="PostalCode"></label>
                    </div>
                    <div class="col-9">
                        <input class="form-control" asp-for="PostalCode" />
                        <span class="text-danger" asp-validation-for="PostalCode"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-9 offset-3">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-info form-control">Submit Application</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

WazeCredit/Views/Home/LoanResult.cshtml
@model WazeCredit.Models.ViewModels.LoanResult

@if (Model.Success)
{
    <h1>Congratulations! Your application has been approved for $@Model.CreditApproved</h1>
    <h3>Your application ID : @Model.CreditID</h3>
}
else
{
    <h1>Your application could not be approved at this point!</h1>
    
    <h3>Following are the reasons for denial:</h3>
    @foreach(var reason in Model.ErrorList)
    {
        <div> &nbsp;-&nbsp; @reason </div>
    }

}

WazeCredit/Views/LifeTime/Index.cshtml
@model List<String>
@{
    ViewData["Title"] = "Index";
}

<h1>LifeTime of Services</h1>
@{
    var count = 0;
}
@foreach (string mess in Model)
{
    if (count == 0)
    {
        <div style="font-size:20px;padding-top:20px;">
            Singleton Lifetime will be same for your application! It changes when the application restarts!
        </div>
    }
    if (count == 2)
    {
        <div style="font-size:20px;padding-top:20px;">
            Scoped Lifetime will be different when you refresh!
        </div>
    }
    if (count == 4)
    {

        <div style="font-size:20px;padding-top:20px;">
            Transient Lifetime will be different for every request!
        </div>
    }
    count++;
    <div>
        @mess
    </div>
}

WazeCredit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WazeCredit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WazeCredit.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WazeCredit</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AllConfigSettings">AppSettings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LifeTime" asp-action="Index">LifeTtime</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LoanApplication">Loan Application</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WazeCredit - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>